/* =====================================================================
 * MazeRunner - SINGLE FILE BUILD
 *
 * GENERATED by tools/make_wokwi_sketch.py - do not edit this file.
 * Edit the real sources in firmware/MazeRunner/ and re-run the script.
 *
 * This is every line of the four firmware files squashed into one, so it
 * can be pasted into a single Wokwi tab (or a single Arduino sketch) with
 * nothing else to set up. It is byte-for-byte the same code as
 *
 *      firmware/MazeRunner/config.h
 *      firmware/MazeRunner/nav_core.h
 *      firmware/MazeRunner/nav_core.cpp
 *      firmware/MazeRunner/MazeRunner.ino
 *
 * Board: Arduino Uno.  Libraries needed: none.
 * ===================================================================== */

#include <stdint.h>
#include <math.h>
#include <string.h>
#include <Wire.h>
#include <EEPROM.h>

/* ---------------------------------------------------------------------
 * Forward declarations - REQUIRED, and the reason is not obvious.
 *
 * The Arduino IDE (and Wokwi) generate a prototype for every function in a
 * .ino and insert them all near the TOP of the file, above the point where
 * the types are defined. A prototype like
 *
 *      static Junction *junction_at(float x, float y, uint8_t create);
 *
 * therefore gets compiled before "struct Junction" exists, and the build
 * dies with "'Junction' does not name a type; did you mean 'union'?" -
 * pointing at a line that is perfectly correct.
 *
 * Declaring the struct names up here fixes it. This is also why they are
 * named structs in the firmware rather than anonymous typedefs: an
 * anonymous "typedef struct {...} X;" cannot be forward-declared at all.
 * --------------------------------------------------------------------- */
struct NavIn;
struct NavOut;
struct Junction;
struct Nav;
struct Sonar;

/* ================= config.h ================= */
/*
 * config.h - ALL tunable numbers live here.
 * This file is shared byte-for-byte between the Arduino firmware and the
 * desktop simulator, so a value tuned in simulation is the value that flies.
 *
 * Units: millimetres (mm), degrees (deg), milliseconds (ms).
 */
#ifndef CONFIG_H
#define CONFIG_H

/* ------------------------------------------------------------------ */
/* 1. ROBOT GEOMETRY - MEASURE YOUR REAL ROBOT AND PUT THE NUMBERS HERE */
/* ------------------------------------------------------------------ */
/* MEASURED on the robot as it stands. Keep these honest - every other
 * number in this file and every simulator result depends on them.
 *
 * TARGET: 220 x 140 mm. Measured across all three maps, five seeds each:
 *      250 x 150 (today)  ->  Map 3 completed  20% of runs
 *      235 x 145          ->  Map 3 completed 100% of runs
 *      220 x 140          ->  Map 3 completed 100% of runs, 92 s
 * The cliff is at a body diagonal of about 280 mm. Losing 10 mm of length
 * and 5 mm of width is enough to cross it. */
#define ROBOT_LENGTH_MM     220.0f   /* nose to tail, including anything that sticks out */
#define ROBOT_WIDTH_MM      115.0f   /* OUTSIDE OF LEFT TYRE TO OUTSIDE OF RIGHT TYRE.
                                        Not the chassis plate - the tyres. This is what
                                        sweeps the circle and what the walls see.       */
#define WHEEL_BASE_MM       (ROBOT_WIDTH_MM - 26.0f)  /* tyre centres: width minus one
                                        tyre width. Sets how fast a given PWM
                                        difference turns the robot, so the turn
                                        feed-forward below is computed from it.         */
#define WHEEL_DIAM_MM        65.0f   /* yellow TT wheel, measure it                    */
#define AXLE_FROM_NOSE_MM   (ROBOT_LENGTH_MM * 0.5f)   /* front bumper to wheel axle. KEEP THIS AT HALF
                                       OF ROBOT_LENGTH_MM: a centred axle gives
                                       the smallest possible pivot circle, and
                                       the pivot circle is what decides whether
                                       the robot can turn in the corridor.     */

/* Where each ultrasonic sits, relative to the wheel-axle centre.
 * x = forward (+), y = left (+), angle = 0 forward, +90 = pointing left. */
#define US_F_X_MM   (ROBOT_LENGTH_MM * 0.5f - 10.0f)
#define US_F_Y_MM     0.0f
#define US_F_ANG      0.0f

/* The side sonars sit ON the wheel-axle line, not ahead of it. That way a
 * gap is seen at the instant the axle draws level with it, which is the
 * moment the robot needs to know about. Measured: moving them back from
 * 40 mm ahead to the axle line is worth about 20 percentage points of
 * completion on Map 3. It costs nothing - just remount them. */
#define US_L_X_MM     0.0f
#define US_L_Y_MM   (ROBOT_WIDTH_MM * 0.5f - 7.0f)
#define US_L_ANG     90.0f

#define US_R_X_MM     0.0f
#define US_R_Y_MM   (-(ROBOT_WIDTH_MM * 0.5f - 7.0f))
#define US_R_ANG    -90.0f

/* ------------------------------------------------------------------ */
/* 2. SENSOR LIMITS                                                    */
/* ------------------------------------------------------------------ */
#define US_MAX_MM          2000     /* anything past this is reported as US_MAX_MM  */
#define US_MIN_MM            25     /* HC-SR04 cannot see closer than ~2 cm         */
#define US_INVALID        60000     /* no echo came back                            */

/* A side reading bigger than this is an opening rather than a wall.
 * A wall beside us reads TARGET_SIDE_MM; an opening one square deep reads
 * TARGET_SIDE_MM + CORRIDOR_MM. Sit between them, biased towards the wall.
 * The old hand-set 420 mm was larger than a one-square opening ever reads,
 * so the robot drove straight past every turn it was meant to take. */
#define OPEN_SIDE_MM     (TARGET_SIDE_MM + (int)(CORRIDOR_MM * 0.45f))
/* An opening only counts on the EDGE wall->open, and only after the reading
 * has been open this many loops. One dropped ping must never invent a
 * junction that is not there. */
#define OPEN_DEBOUNCE         9
/* A front reading smaller than this means "wall ahead, start setting up".
 * At a square's centre a wall in the next square reads 37 mm, and a wall two
 * squares away reads 342 mm, so 200 mm triggers about one square early. */
#define FRONT_BLOCKED_MM    200
/* ...and bigger than this means "the way ahead is open for at least one more
 * square" (342 mm at a square centre, so 260 mm has margin both ways). */
#define FRONT_OPEN_MM       260
/* Lining up on a wall ahead.
 *
 * We want the wheel AXLE in the middle of the junction square before we
 * pivot, which means the wall should end up CORRIDOR_MM/2 = 152 mm from the
 * axle. The front sonar sits US_F_X_MM = 115 mm ahead of the axle, so it
 * would have to read 37 mm - and an HC-SR04 is not trustworthy under about
 * 40 mm.
 *
 * So we range off the wall down to a reading we can believe, then hand over
 * to the wheel encoders for the last few centimetres. */
#define FRONT_HANDOVER_MM   100     /* switch from sonar to encoders here   */
/* Where to stop before a 90 degree pivot, measured back from the middle of
 * the junction square. A full 360 pivot sweeps the same circle wherever you
 * stand, but a QUARTER turn does not: sitting further back gives the front
 * corner room to swing into. In a passage this tight that is worth real
 * points, so the number is measured, not guessed - see docs/10_MAP_NOTES.md */
#define PIVOT_BACKOFF_MM     40
/* Closer than this: reverse before doing anything else. Must stay well
 * below FRONT_HANDOVER_MM or the robot reverses out of its own approach. */
#define FRONT_TOOCLOSE_MM    25

/* ------------------------------------------------------------------ */
/* 3. MAZE ASSUMPTIONS                                                 */
/* ------------------------------------------------------------------ */
#define CORRIDOR_MM         305     /* 1 ft grid, from the organisers' spreadsheet  */
#define CELL_MM             305     /* one "step" of the maze grid = 1 ft           */
/* DERIVED - do not hand-edit. Change the geometry above and these follow.
 *
 * Getting these wrong by hand is what cost the most time on this project:
 * a threshold tuned for one body width silently stops working when the body
 * changes, and the symptom looks like a navigation bug rather than a number.
 *
 * Dead centre of the passage, as the side sensor sees it. */
#define TARGET_SIDE_MM   ((int)(CORRIDOR_MM * 0.5f - US_L_Y_MM))

/* ------------------------------------------------------------------ */
/* 4. SPEEDS  (PWM counts, 0..255)                                     */
/* ------------------------------------------------------------------ */
#define PWM_MIN              55     /* below this a TT motor just buzzes            */
#define PWM_MAX             255
/* Straight-line speed. Measured over 6 seeds x 3 maps nominal, then 13
 * seeds x 2 hands x 3 maps with deliberately bad hardware (2.5x wheel slip,
 * 4x sonar noise, 3x dropout, 2.3x gyro bias, 15% battery sag):
 *
 *      cruise   total time   complete   wall contact, degraded
 *        110       182 s       100%       -
 *        140       147 s       100%       -
 *        170       128 s       100%       100 episodes
 *        200       116 s       100%         0 episodes     <- shipped
 *        230       108 s       100%         0 episodes
 *
 * 170 used to be the ceiling because Map 2 fell apart above it. That was
 * never really about speed: it was the two pivots in the open crossing, and
 * STRAIGHT_FIRST deleted them. With those gone the whole curve moved.
 *
 * 200 rather than 230 for one reason you can see in the mixer: steering is
 * added to cruise and then clamped at 255, so a cruise of 200 with
 * STEER_LIMIT 80 can still swing 135 counts of differential, and 230 only
 * 105. That headroom is what corrects a bad approach to a corner.
 *
 * If the real track is slippier than the model, drop to 170 - you lose 12
 * seconds and every hard correction gets its full authority back. */
#define PWM_CRUISE          200
#define PWM_SLOW             95     /* creeping / approaching a wall                */
#define PWM_TURN            110
#define PWM_BACK             95     /* reversing                                    */

/* ------------------------------------------------------------------ */
/* 5. CONTROL GAINS                                                    */
/* ------------------------------------------------------------------ */
#define KP_WALL            0.42f    /* PWM per mm of side error                     */
#define KD_WALL            2.10f    /* PWM per (mm/s) of side error rate            */
#define KP_HEADING         3.20f    /* PWM per degree of heading error (straights)  */
/* Yaw-rate damping. The gyro measures how fast we are turning, so we can
 * subtract it and stop the robot weaving down a straight instead of only
 * reacting after the heading has already gone wrong. This is the single
 * biggest "makes it look smooth" term in the whole file. */
#define KD_YAW             0.00f
#define STEER_LIMIT          80     /* max differential PWM applied while driving   */
/* Never step a motor by more than this in one 20 ms tick. Sudden steps make
 * the tyres slip, and slipping wheels are lying wheels. */
#define PWM_SLEW             255

/* ---- turning ----
 * The firmware can drive a proper trapezoidal turn profile - ramp up, hold,
 * ramp down - which is what serious micromouse code does
 * (see github.com/ukmars/mazerunner-core). It is implemented and it works.
 *
 * It is switched OFF here, because it was measured and it LOST:
 *
 *      no profile   map1  83%   map2 100%   map3  50%   avg 78%
 *      profile on   map1  83%   map2  83%   map3  50%   avg 72%
 *
 * Motion profiles pay off when you have wheel-speed PID running off
 * high-resolution encoders and you are trying to corner at speed. With 20
 * ticks per wheel revolution and a passage that leaves 28 mm a side, the
 * plain PD controller reacts faster and wins. Leaving OMEGA and ALPHA huge
 * makes the profile effectively instant, i.e. a plain PD.
 *
 * If you ever fit better encoders, set OMEGA to about 150 and ALPHA to 1000
 * and re-run the sweep - the code is all still here. */
/* Top turn rate. Must be reachable inside PWM_TURN:
 *      omega_max = (PWM_TURN - PWM_MIN) / TURN_FF
 * Asking for more than the motors can give just saturates the loop and
 * throws away the whole point of having a profile. */
#define TURN_OMEGA_DPS    600.0f
#define TURN_ALPHA_DPS2  20000.0f
#define V_MAX_MMS         380.0f    /* wheel speed at PWM 255, loaded. Measure it   */
#define KP_TURN            2.60f    /* PWM per degree of error against the profile  */
#define KD_TURN            0.22f    /* PWM per (deg/s) of rate error                */
/* Feed-forward: the PWM that ALREADY produces the rate we are asking for, so
 * the PD terms only have to correct the difference. Straight from geometry. */
#define TURN_FF   (WHEEL_BASE_MM * 0.5f / 57.29578f * (255.0f - PWM_MIN) / V_MAX_MMS)
#define TURN_TOL_DEG       3.0f     /* pivot is finished inside this error          */
#define TURN_SETTLE_MS      120     /* ...and must stay inside it this long         */
#define TURN_TIMEOUT_MS    2600     /* give up and move on                          */


/* ------------------------------------------------------------------ */
/* 5b. STAYING SQUARE WITH THE MAZE                                    */
/* ------------------------------------------------------------------ */
/* How hard to trust the walls over the gyro when both walls are in view.
 * A pivot that finishes three degrees short is invisible to the gyro,
 * because the heading was re-zeroed onto the target - but three degrees is
 * 16 mm of drift per foot, and two corners later it is a wall. The walls
 * themselves are the only absolute reference the robot has. See
 * "corridor-parallel correction" in nav_core.cpp. */
#define WALL_ALIGN_GAIN    0.35f
#define WALL_ALIGN_MM      70.0f    /* travel between angle estimates       */

/* Livelock guard. Deciding this many times inside this little travel means
 * the robot is turning on the spot arguing with itself, which is how a run
 * quietly burns three minutes without going anywhere. */
#define DECIDE_BURST_MAX      3
#define DECIDE_BURST_MM   250.0f
#define DECIDE_LOCKOUT_MM 350.0f

/* ------------------------------------------------------------------ */
/* 6. TIMING                                                           */
/* ------------------------------------------------------------------ */
#define LOOP_HZ              50
#define LOOP_DT_MS           20
#define BACKUP_MS           420
/* Roll this far past a side opening before pivoting into it. Ideal value is
 *      CORRIDOR_MM / 2 + US_L_X_MM - (debounce lag, about 45 mm) = 145 */
#define CREEP_AFTER_OPEN_MM 147
#define TURN_SETTLE_IN_MS   260     /* stop dead before pivoting; also the
                                       window used to re-measure gyro bias  */
/* How long a hand must stay in front of the nose before it arms the start.
 * A single bad ping must never be able to launch a run - see ST_WAIT_START
 * in nav_core.cpp for the power-on false start this prevents. */
#define START_ARM_MS        300
#define STUCK_WINDOW_MS     900     /* no encoder movement this long = stuck         */
#define RUN_TIMEOUT_MS   240000UL   /* 4 minutes then stop, whatever happens         */

/* ------------------------------------------------------------------ */
/* 7. ODOMETRY                                                         */
/* ------------------------------------------------------------------ */
#define ENC_TICKS_PER_REV    20     /* slots in the black encoder disc              */
#define ENC_MM_PER_TICK    (3.14159265f * WHEEL_DIAM_MM / (float)ENC_TICKS_PER_REV)

/* ------------------------------------------------------------------ */
/* 8. FEATURE SWITCHES                                                 */
/* ------------------------------------------------------------------ */
#define HAS_GYRO              1     /* MPU-6050 fitted                              */
#define HAS_ENCODERS          1     /* LM393 slot sensors fitted                    */
/* Floor line sensor: REMOVED. Do not fit one, do not buy one.
 *
 * You asked whether dropping it would make things work better. It does, and
 * not because it was useless - because it was dangerous.
 *
 * What it did:  counted the black sector lines for telemetry, and watched
 * for the striped start/finish gate as a second way to notice the run was
 * over.
 *
 * What it cost:  the gate detector fires on four black-to-white edges
 * arriving inside 350 ms. A TCRT5000 is a comparator with a trim pot, and
 * when it crosses a strip of tape at an angle its output CHATTERS around
 * the threshold - four edges is easy. The robot would then declare itself
 * finished in the middle of the maze and stop. That is a whole map lost, to
 * a sensor that was never steering anything.
 *
 * Measured with it off: 24 runs, 24 complete, same times to a tenth of a
 * second, every sector line still crossed. The robot notices the finish by
 * driving into open space on all three sonars, which is what actually fired
 * on every single run in this repository anyway.
 *
 * The code is still here behind this switch. Set it back to 1 only if you
 * fit a sensor and can show it does something the sonars cannot. */
#define HAS_LINE_SENSOR       0     /* TCRT5000 looking at the floor - NOT FITTED   */

/* Which hand do we keep on the wall?  +1 = LEFT hand, -1 = RIGHT hand.
 *
 * This used to be the most dangerous number in the file. It is now very
 * nearly a free choice, and that is worth understanding.
 *
 * BEFORE straight-first (below), the hand decided whether you scored:
 *
 *              road covered     left hand    right hand
 *      Map 1                       100%         100%
 *      Map 2                        50%         100%     <-- half a map
 *      Map 3                       100%         100%
 *
 * On Map 2 the left hand turned straight out of the exit the first time it
 * reached the crossing and skipped the entire lower loop.
 *
 * AFTER straight-first, both hands drive the IDENTICAL route on all three
 * maps - same squares, same order, same time to a tenth of a second, 8 seeds
 * each. The robot goes straight through the crossing rather than turning at
 * it, so there is no longer a turn there for the hand to get wrong.
 *
 * Left as RIGHT because it is the one that was right before as well: if a
 * future map does put a real choice back in, the right hand is the one with
 * the measurements behind it. */
#define WALL_HAND            (-1)

/* Go STRAIGHT through a crossing whenever the way ahead is open, and only
 * consult the hand rule when it is not.
 *
 * This is the single highest-value line in the file, for three reasons.
 *
 * 1. It is the route you drew on Map 2. Straight down the middle to the
 *    bottom row, round the lower loop, back along the middle and out.
 *
 * 2. It never pivots in the open crossing. Map 2 has one 4-way crossing,
 *    and a pivot there is the worst pivot on the whole course: with no wall
 *    on either side there is nothing to square up against, so a turn that
 *    finishes a few degrees short stays short. Every livelock this project
 *    ever had started in that square. Straight-first drives through it
 *    twice without turning at all - 6 pivots on Map 2 become 4.
 *
 * 3. It makes WALL_HAND stop mattering. Measured at grid level, left hand
 *    and right hand now produce the IDENTICAL route on all three maps. The
 *    old left-hand rule turned straight out of the Map 2 exit and skipped
 *    the whole loop; it cannot any more. Picking the wrong hand at the
 *    start line used to cost a map. Now it costs nothing.
 *
 * The catch, stated honestly: straight-first on its own is NOT a complete
 * coverage rule. In a maze with a dead-end stub it can walk out of a
 * crossing that still has road left in it (measured: 5 squares of 11 on a
 * test maze built to provoke exactly that). None of the three competition
 * maps has a dead end - every square of road is on a through route, checked
 * by build_maps.py - so it is safe here. MODE_TREMAUX is what closes the
 * hole for good, and it costs nothing to run: see DEFAULT_MODE below. */
#define STRAIGHT_FIRST        1

/* Navigation mode */
#define MODE_WALLFOLLOW       0     /* simple, never gets confused in a plain maze  */
#define MODE_TREMAUX          1     /* remembers junctions, beats loops and islands */
/* Wall following, not Tremaux - but only just, and here is the honest
 * comparison so you can flip it with your eyes open.
 *
 * On the three competition maps the two modes are now INDISTINGUISHABLE:
 * 8 seeds x 3 maps x both hands, every combination completes 100% of runs,
 * covers 100% of the road, scores every sector line, and finishes within a
 * tenth of a second of the others. Straight-first is what made them agree.
 *
 * Wall following is the default because it is the simpler machine: it has no
 * dependence on odometry at all, and odometry is the least trustworthy thing
 * on the robot.
 *
 * Switch to MODE_TREMAUX if a future map has a DEAD END in it. That is the
 * one case straight-first cannot handle on its own - it can walk out of a
 * crossing that still has undriven road behind it. Measured on a test maze
 * built to provoke exactly that: wall following alone covers 5 squares of
 * 11, Tremaux covers 11 of 11. It costs 4 bytes of SRAM per junction and
 * nothing to buy. build_maps.py prints a dead-end warning per map. */
#define DEFAULT_MODE   MODE_WALLFOLLOW

/* Tremaux memory */
#define MAX_JUNCTIONS        48     /* 48 * 5 bytes = 240 bytes of SRAM             */
#define EEPROM_MAGIC       0x4D5A   /* 'MZ'                                          */
#define EEPROM_BASE           0

/* ------------------------------------------------------------------ */
/* 9. ARDUINO PIN MAP  (Uno R3)                                        */
/* ------------------------------------------------------------------ */
#define PIN_ENC_L      2   /* INT0 - left  wheel slot sensor          */
#define PIN_ENC_R      3   /* INT1 - right wheel slot sensor          */
#define PIN_IN1        4   /* L298N                                    */
#define PIN_ENA        5   /* L298N, PWM, RIGHT motor                  */
#define PIN_ENB        6   /* L298N, PWM, LEFT  motor                  */
#define PIN_IN2        7
#define PIN_IN3        8
#define PIN_TRIG_R     9
#define PIN_ECHO_R    10
#define PIN_IN4       11
#define PIN_LINE      12   /* was the TCRT5000 - not fitted, see
                              HAS_LINE_SENSOR. The pin now carries the
                              GO button instead.                       */
/* GO button: button between this pin and GND, nothing else. The internal
 * pull-up does the rest, so there is no resistor to fit and no way to wire
 * it wrong.
 *
 * It used to share D13 with the status LED, because the line sensor owned
 * D12. That meant flipping D13 between OUTPUT and INPUT_PULLUP a hundred
 * times a second to sample it, with a 330 ohm resistor to stop the press
 * shorting the LED drive - and in Wokwi it simply did not register presses.
 * Dropping the line sensor freed D12, so the button gets its own pin and
 * the whole trick goes away. */
#define PIN_GO        12
#define PIN_LED       13   /* onboard LED + optional buzzer. OUTPUT only */
#define PIN_TRIG_F   A0
#define PIN_ECHO_F   A1
#define PIN_TRIG_L   A2
#define PIN_ECHO_L   A3
/*      A4 = SDA, A5 = SCL  -> MPU-6050, do not use for anything else  */

/* The GO button took over the line sensor's pin. If you ever refit a line
 * sensor, one of them has to move - and a silent clash would show up as the
 * robot starting itself whenever it drove over black tape, which is a
 * miserable thing to debug in a competition hall. */
#if HAS_LINE_SENSOR && (PIN_GO == PIN_LINE)
#error "PIN_GO and PIN_LINE are both D12. Move one before fitting a line sensor."
#endif

/* Motor polarity: flip to -1 if a wheel spins backwards after wiring. */
#define MOTOR_L_SIGN  (+1)
#define MOTOR_R_SIGN  (+1)

#endif /* CONFIG_H */

/* ================= nav_core.h ================= */
/*
 * nav_core.h - the robot's brain.
 *
 * THIS FILE CONTAINS NO ARDUINO CODE AT ALL.
 * It is plain C++ with only <stdint.h>, which means the exact same source
 * is compiled twice:
 *
 *   1. into MazeRunner.ino, which runs on the Arduino Uno
 *   2. into libnavcore.so, which the Python simulator drives
 *
 * So whatever behaviour you see in the simulator is, literally, the
 * behaviour of the firmware. Tune in sim, flash, drive.
 */
#ifndef NAV_CORE_H
#define NAV_CORE_H


#ifdef _WIN32
#define NAV_API extern "C" __declspec(dllexport)
#else
#define NAV_API extern "C"
#endif

/* ---------------- what the brain is told, every 20 ms ---------------- */
struct NavIn {
    uint16_t dist_front_mm;   /* US_MAX_MM when nothing is in range        */
    uint16_t dist_left_mm;
    uint16_t dist_right_mm;
    float    heading_deg;     /* continuous, CCW positive, 0 = start pose  */
    float    gyro_rate_dps;   /* yaw rate, CCW positive                    */
    int32_t  ticks_left;      /* cumulative, signed                        */
    int32_t  ticks_right;
    uint8_t  line_black;      /* 1 = floor sensor is over a black mark     */
    uint8_t  start_signal;    /* 1 = judge said go                         */
    uint16_t dt_ms;
};

/* ---------------- what the brain answers ---------------- */
struct NavOut {
    int16_t pwm_left;         /* -255 .. +255                              */
    int16_t pwm_right;
    uint8_t state;            /* NavState                                  */
    uint8_t done;             /* 1 = finished, stop the run                */
    uint8_t led;              /* 1 = light/beep                            */
    uint16_t sectors_seen;    /* black marks counted by the floor sensor    */
    float   dbg_target_deg;
    float   dbg_steer;
};

typedef enum {
    ST_BOOT = 0,
    ST_WAIT_START,
    ST_COUNTDOWN,
    ST_DRIVE,
    ST_CREEP,          /* rolling forward so the axle reaches the junction */
    ST_BACKUP,
    ST_TURN,
    ST_STUCK_RECOVER,
    ST_FINISH,
    ST_NUM_STATES
} NavState;

/* ---------------- API ---------------- */
NAV_API void        nav_reset(uint8_t mode, int8_t hand);
NAV_API void        nav_step(const NavIn *in, NavOut *out);
NAV_API const char *nav_state_name(uint8_t s);

/* Introspection, used by the simulator's telemetry log and by the
 * Arduino's serial debug output. */
NAV_API int32_t     nav_odom_x_mm(void);
NAV_API int32_t     nav_odom_y_mm(void);
NAV_API int32_t     nav_junction_count(void);
NAV_API uint32_t    nav_memory_bytes(void);

/* Tremaux memory, exposed so the .ino can mirror it into the Uno's
 * built-in 1 kB EEPROM (no external memory chip is needed). */
NAV_API uint32_t    nav_export_memory(uint8_t *buf, uint32_t buf_len);
NAV_API void        nav_import_memory(const uint8_t *buf, uint32_t buf_len);

#endif /* NAV_CORE_H */

/* ================= nav_core.cpp ================= */
/*
 * nav_core.cpp - navigation brain, shared by the Arduino and the simulator.
 * Plain C++ only. No Arduino API. No dynamic memory.
 */

#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif
#define DEG2RAD (float)(M_PI / 180.0)
#define RAD2DEG (float)(180.0 / M_PI)

/* ------------------------------------------------------------------ */
/* small helpers                                                       */
/* ------------------------------------------------------------------ */
static float wrap180(float a)
{
    while (a > 180.0f)  a -= 360.0f;
    while (a < -180.0f) a += 360.0f;
    return a;
}

static int16_t clamp16(float v, int16_t lo, int16_t hi)
{
    if (v < (float)lo) return lo;
    if (v > (float)hi) return hi;
    return (int16_t)v;
}

/* A TT motor does nothing below PWM_MIN. Push small commands up to the
 * threshold so the PD loop keeps authority instead of silently dying. */
static int16_t deadband(int16_t v)
{
    if (v == 0) return 0;
    if (v > 0 && v < PWM_MIN)  return PWM_MIN;
    if (v < 0 && v > -PWM_MIN) return -PWM_MIN;
    return v;
}

/* Never step a motor command by more than PWM_SLEW in one tick. A sudden
 * jump makes the tyres slip, and a slipping wheel reports distance it never
 * travelled. */
static int16_t slew(int16_t prev, int16_t want)
{
    int16_t d = (int16_t)(want - prev);
    if (d >  PWM_SLEW) return (int16_t)(prev + PWM_SLEW);
    if (d < -PWM_SLEW) return (int16_t)(prev - PWM_SLEW);
    return want;
}

/* direction index: 0 = +X (the way we faced at the start), 1 = +Y (left),
 * 2 = -X, 3 = -Y. */
static uint8_t dir_of_heading(float h)
{
    int d = (int)floorf((wrap180(h) + 45.0f) / 90.0f);
    d &= 3;
    return (uint8_t)d;
}

/* ------------------------------------------------------------------ */
/* Tremaux junction memory - 4 bytes per junction, lives in SRAM and is  */
/* mirrored into the Uno's built-in 1 kB EEPROM by the .ino.            */
/* ------------------------------------------------------------------ */
/* 4 bytes each. Position is stored in units of 50 mm, which covers a 6 m
 * maze in a signed byte and is finer than we can navigate anyway.
 *
 * A NAMED struct, not an anonymous "typedef struct {...} Junction;", and
 * that matters for one specific reason: the Arduino IDE auto-generates a
 * prototype for every function and inserts them ABOVE the type definitions.
 * A prototype mentioning Junction then fails to compile unless Junction can
 * be forward-declared - and an anonymous typedef cannot be. Same for Nav
 * below and Sonar in the .ino. See tools/make_wokwi_sketch.py. */
struct Junction {
    int8_t  qx, qy;      /* position / 50 mm                              */
    uint8_t marks;       /* 2 bits per direction, value 0..2              */
    uint8_t used;
};
#define JUNC_UNIT_MM   50.0f
#define JUNC_MATCH_MM 260.0f

struct Nav {
    /* configuration */
    uint8_t mode;
    int8_t  hand;              /* +1 left-hand rule, -1 right-hand rule   */

    /* state machine */
    uint8_t state;
    uint32_t t_ms;             /* time since nav_reset                    */
    uint32_t state_t_ms;       /* time in current state                   */
    uint32_t run_t_ms;         /* time since the run actually started     */

    /* odometry */
    int32_t prev_tl, prev_tr;
    uint8_t odom_primed;
    float   gyro_bias;         /* dps, re-estimated every time we stop     */
    float   bias_acc;
    uint16_t bias_n;
    uint32_t still_ms;
    float   x_mm, y_mm;        /* position, start pose = (0,0)            */
    float   heading;           /* degrees, continuous                     */
    float   heading_ref;       /* gyro reading that corresponds to 0 deg  */
    float   dist_total_mm;
    float   dist_since_decision_mm;
    float   dist_open_mm;      /* how far we have driven fully in the open */
    float   last_d_mm;         /* |distance| covered in the last tick      */

    /* driving */
    float   target_deg;        /* heading we want to hold, multiple of 90 */
    float   prev_side_err;
    float   par_ref_diff;      /* corridor-parallel estimator             */
    float   par_ref_dist;
    uint8_t par_valid;
    float   last_decide_mm;    /* livelock guard                          */
    float   no_decide_until_mm;
    uint8_t decide_burst;
    float   creep_target_mm;
    float   backup_start_mm;

    /* turning - a trapezoidal profile, generated fresh for every pivot */
    float   turn_from_deg;     /* heading when the pivot started          */
    float   turn_total_deg;    /* how far to go, signed                   */
    float   turn_prof_deg;     /* how far the profile has swept so far    */
    float   turn_prof_dps;     /* the rate the profile is asking for      */
    int16_t out_l, out_r;      /* last commanded PWM, for the slew limit  */
    uint32_t turn_ok_ms;
    uint8_t  turn_retries;
    uint8_t  resume_turn;      /* back up, then finish the turn we started */
    int16_t  last_cmd_mag;

    /* decision snapshot, captured the instant we spot a junction */
    uint8_t snap_left, snap_front, snap_right;
    uint8_t open_cnt_l, open_cnt_r, open_cnt_f;   /* debounce integrators  */
    uint8_t open_l, open_r, open_f;   /* debounced "there is a gap" flags  */
    uint8_t creep_by_front;           /* aligning on a wall, not on odometry */

    /* stuck detector */
    int32_t stuck_tl, stuck_tr;
    uint32_t stuck_ms;
    uint8_t  stuck_escapes;

    /* floor line sensor */
    uint8_t  line_prev;
    uint16_t sectors;
    uint32_t last_edge_ms;
    uint8_t  edge_burst;

    /* memory */
    Junction junc[MAX_JUNCTIONS];
    uint8_t  njunc;
    uint8_t  last_dir;

    /* misc */
    uint8_t  first_decision_done;
    uint8_t  start_armed;
    uint32_t arm_ms;
    uint8_t  done;
};

static Nav g;

/* ------------------------------------------------------------------ */
/* Find the junction we are standing in.
 *
 * Matching is by proximity, not by an exact cell index, because after a
 * few metres the encoders have drifted and an exact match would file the
 * same corner twice and the memory would be worthless.
 *
 * The useful side effect: when we DO recognise a junction, we trust the
 * position we recorded the first time and snap the odometry back onto it.
 * That is loop closure, and it stops drift accumulating lap after lap. */
static Junction *junction_at(float x, float y, uint8_t create)
{
    Junction *best = 0;
    float best_d2 = JUNC_MATCH_MM * JUNC_MATCH_MM;

    for (uint8_t i = 0; i < g.njunc; i++) {
        if (!g.junc[i].used) continue;
        float dx = (float)g.junc[i].qx * JUNC_UNIT_MM - x;
        float dy = (float)g.junc[i].qy * JUNC_UNIT_MM - y;
        float d2 = dx * dx + dy * dy;
        if (d2 < best_d2) { best_d2 = d2; best = &g.junc[i]; }
    }
    if (best) {
        if (create) {
            g.x_mm = (float)best->qx * JUNC_UNIT_MM;
            g.y_mm = (float)best->qy * JUNC_UNIT_MM;
        }
        return best;
    }
    if (!create || g.njunc >= MAX_JUNCTIONS) return 0;
    Junction *j = &g.junc[g.njunc++];
    j->qx = (int8_t)lroundf(x / JUNC_UNIT_MM);
    j->qy = (int8_t)lroundf(y / JUNC_UNIT_MM);
    j->marks = 0; j->used = 1;
    return j;
}

static uint8_t mark_get(const Junction *j, uint8_t dir)
{
    return (uint8_t)((j->marks >> (dir * 2)) & 0x3);
}

static void mark_inc(Junction *j, uint8_t dir)
{
    uint8_t v = mark_get(j, dir);
    if (v < 2) v++;
    j->marks = (uint8_t)((j->marks & ~(0x3 << (dir * 2))) | (v << (dir * 2)));
}

/* Everything that has to be forgotten when we start driving again.
 *
 * The opening flags in particular: they describe a junction we have already
 * dealt with, and if a turn ends through the timeout or the jam-recovery
 * path instead of the normal one, a stale flag makes the robot invent a
 * junction a few centimetres later and turn off the route. */
static void enter_drive_ex(uint8_t after_turn)
{
    g.prev_side_err = 0.0f;
    g.dist_since_decision_mm = 0.0f;
    g.snap_left = g.snap_right = g.snap_front = 0;
    g.creep_by_front = 0;
    if (after_turn) {
        /* A pivot changes what "left" and "right" point at, so the running
         * measurements are meaningless and have to start again. */
        g.open_cnt_l = g.open_cnt_r = g.open_cnt_f = 0;
        g.open_l = g.open_r = g.open_f = 0;
    }
    g.state = ST_DRIVE;
    g.state_t_ms = 0;
}

/* Straight on through a junction: the latched decision is finished with, but
 * the live sensor picture is still valid and throwing it away leaves the
 * robot blind for the next 200 ms - which is exactly long enough to miss the
 * turn that comes immediately afterwards. */
static void enter_drive(void)       { enter_drive_ex(0); }
static void enter_drive_turned(void){ enter_drive_ex(1); }

/* ------------------------------------------------------------------ */
NAV_API void nav_reset(uint8_t mode, int8_t hand)
{
    memset(&g, 0, sizeof(g));
    g.mode  = mode;
    g.hand  = (hand >= 0) ? +1 : -1;
    g.state = ST_BOOT;
    g.target_deg = 0.0f;
}

/* ------------------------------------------------------------------ */
static void odom_update(const NavIn *in)
{
    if (!g.odom_primed) {
        g.prev_tl = in->ticks_left;
        g.prev_tr = in->ticks_right;
        g.heading_ref = in->heading_deg;
        g.odom_primed = 1;
        return;
    }

    float dl = (float)(in->ticks_left  - g.prev_tl) * ENC_MM_PER_TICK;
    float dr = (float)(in->ticks_right - g.prev_tr) * ENC_MM_PER_TICK;
    g.prev_tl = in->ticks_left;
    g.prev_tr = in->ticks_right;

    float d = 0.5f * (dl + dr);

    /* Pivoting in place must not move the position estimate. The two wheels
     * are never perfectly matched, so (dl+dr)/2 comes out a few millimetres
     * short of zero on every single turn, and forty turns later the robot
     * thinks it is a quarter of a metre from where it is. Detect the pivot
     * and throw the translation away. */
    {
        float adl = dl < 0 ? -dl : dl;
        float adr = dr < 0 ? -dr : dr;
        float ad  = d  < 0 ? -d  : d;
        if (ad < 0.35f * (adl + adr)) d = 0.0f;
    }

#if HAS_GYRO
    /* Integrate the gyro here rather than in the hardware layer, so the
     * drift handling is part of the code the simulator tests.
     *
     * Two things keep an MPU-6050 honest over a four minute run:
     *   - re-measure the zero-rate bias every time we are standing still,
     *     which happens for a moment before every single pivot;
     *   - a deadband, so the noise floor cannot random-walk the heading
     *     while we drive down a straight.
     * Without both, the bias alone is worth 15-20 degrees per run, and a
     * robot 20 degrees out of square wedges itself in the first corner. */
    if (g.last_cmd_mag == 0) {
        g.still_ms += in->dt_ms;
        if (g.still_ms > 150) {              /* let the chassis stop ringing */
            g.bias_acc += in->gyro_rate_dps;
            g.bias_n++;
        }
    } else {
        if (g.bias_n > 4) {
            float est = g.bias_acc / (float)g.bias_n;
            g.gyro_bias += 0.5f * (est - g.gyro_bias);
        }
        g.bias_acc = 0.0f; g.bias_n = 0; g.still_ms = 0;
    }

    float rate = in->gyro_rate_dps - g.gyro_bias;
    if (rate > -0.40f && rate < 0.40f) rate = 0.0f;
    g.heading = wrap180(g.heading + rate * (in->dt_ms / 1000.0f));
#else
    g.heading = wrap180(g.heading + (dr - dl) / WHEEL_BASE_MM * RAD2DEG);
#endif

    float hr = g.heading * DEG2RAD;
    g.x_mm += d * cosf(hr);
    g.y_mm += d * sinf(hr);

    if (d < 0) d = -d;
    g.last_d_mm                = d;
    g.dist_total_mm           += d;
    g.dist_since_decision_mm  += d;
}

/* Count black floor marks. Each sector line gives one black->white edge.
 * A start/finish gate is painted as stripes, so it gives a fast burst of
 * edges - that is how we know we are out. */
static void line_update(const NavIn *in)
{
#if HAS_LINE_SENSOR
    if (in->line_black != g.line_prev) {
        if (g.line_prev == 1) {          /* leaving black = crossed a mark */
            g.sectors++;
        }
        if (g.t_ms - g.last_edge_ms < 350) {
            if (g.edge_burst < 255) g.edge_burst++;
        } else {
            g.edge_burst = 0;
        }
        g.last_edge_ms = g.t_ms;
        g.line_prev = in->line_black;
    }
#else
    (void)in;
#endif
}

/* ------------------------------------------------------------------ */
/* Corridor-parallel correction.
 *
 * A pivot that finishes three degrees short is invisible to the robot: the
 * gyro was re-zeroed onto the target, so as far as it knows it is straight.
 * Three degrees is 16 mm of drift per foot travelled, and two corners later
 * it is scraping a wall or turning the wrong way at a junction.
 *
 * With both walls in view the maze itself will tell us. As the robot drives,
 *      d(left gap)/ds = -tan(phi)    d(right gap)/ds = +tan(phi)
 * so the difference between them changes at 2*tan(phi) per millimetre. That
 * is an absolute angle measured against the walls, not against the gyro, and
 * it is what lets the heading estimate be pulled back onto the truth.
 * ------------------------------------------------------------------ */
static void wall_align(const NavIn *in, uint8_t have_l, uint8_t have_r)
{
    if (!(have_l && have_r)) { g.par_valid = 0; return; }

    float diff = (float)in->dist_left_mm - (float)in->dist_right_mm;
    if (!g.par_valid) {
        g.par_ref_diff = diff;
        g.par_ref_dist = g.dist_total_mm;
        g.par_valid = 1;
        return;
    }
    float ds = g.dist_total_mm - g.par_ref_dist;
    if (ds < WALL_ALIGN_MM) return;

    float slope = (diff - g.par_ref_diff) / ds;          /* mm per mm      */
    float phi   = -RAD2DEG * atanf(slope * 0.5f);        /* degrees crooked */
    if (phi >  12.0f) phi =  12.0f;
    if (phi < -12.0f) phi = -12.0f;

    /* If we are phi degrees off the corridor, then our heading really is
     * target + phi. Blend towards that rather than jumping, because one
     * noisy pair of readings should not rewrite the heading. */
    g.heading += WALL_ALIGN_GAIN * (wrap180(g.target_deg + phi - g.heading));

    g.par_ref_diff = diff;
    g.par_ref_dist = g.dist_total_mm;
}

/* ------------------------------------------------------------------ */
/* straight-line steering: centre in the corridor, hug one wall if only  */
/* one is there, and always let the gyro veto long-term drift.           */
/* ------------------------------------------------------------------ */
static float steer_command(const NavIn *in, float dt_s)
{
    uint8_t have_l = (in->dist_left_mm  < OPEN_SIDE_MM);
    uint8_t have_r = (in->dist_right_mm < OPEN_SIDE_MM);
    wall_align(in, have_l, have_r);

    /* Sign convention, and it matters: side_err > 0 means "we are too far
     * to the LEFT and need to move right". All three cases below have to
     * agree on that, and the steering term is then subtracted. */
    float side_err = 0.0f;
    uint8_t side_valid = 1;

    if (have_l && have_r) {
        side_err = (float)in->dist_right_mm - (float)in->dist_left_mm;
        side_err *= 0.5f;
    } else if (have_l) {
        side_err = (float)TARGET_SIDE_MM - (float)in->dist_left_mm;
    } else if (have_r) {
        side_err = (float)in->dist_right_mm - (float)TARGET_SIDE_MM;
    } else {
        side_valid = 0;
    }

    float steer = 0.0f;
    if (side_valid) {
        float derr = (side_err - g.prev_side_err) / (dt_s > 0.0f ? dt_s : 0.02f);
        /* clamp the derivative: a sonar dropout must not slam the wheels */
        if (derr >  600.0f) derr =  600.0f;
        if (derr < -600.0f) derr = -600.0f;
        steer = -(KP_WALL * side_err + KD_WALL * (derr * 0.001f));
        g.prev_side_err = side_err;
    } else {
        g.prev_side_err = 0.0f;
    }

    /* Heading hold. With walls present it is a gentle trim; with no walls
     * it is the only thing keeping us straight. */
    float herr = wrap180(g.target_deg - g.heading);
    float hterm = KP_HEADING * herr;
    steer += side_valid ? (hterm * 0.35f) : hterm;

    /* Yaw-rate damping. The gyro says how fast we are turning right now, so
     * we can cancel it instead of waiting for the heading to go wrong and
     * then chasing it. This is what stops the robot weaving down a straight,
     * and weaving is what puts a corner into a wall three metres later. */
    steer -= KD_YAW * in->gyro_rate_dps;

    if (steer >  (float)STEER_LIMIT) steer =  (float)STEER_LIMIT;
    if (steer < -(float)STEER_LIMIT) steer = -(float)STEER_LIMIT;
    return steer;
}

/* ------------------------------------------------------------------ */
/* choose where to go at a junction                                     */
/* ------------------------------------------------------------------ */
/* returns a turn in units of 90 deg: +1 left, 0 straight, -1 right, 2 = U */
static int8_t choose_turn(void)
{
    uint8_t openL = g.snap_left;
    uint8_t openF = g.snap_front;
    uint8_t openR = g.snap_right;

    /* Straight beats everything. Not turning is always cheaper and always
     * safer than turning: a pivot costs a second, and a pivot in an open
     * crossing has no wall to square up against afterwards. See
     * STRAIGHT_FIRST in config.h for what this is worth on Map 2.
     *
     * In MODE_TREMAUX this is only the PREFERENCE order, further down - the
     * marks still get the final say, which is what keeps coverage safe in a
     * maze with dead ends. Here it is an outright rule, because plain wall
     * following has no marks to consult. */
#if STRAIGHT_FIRST
    if (g.mode == MODE_WALLFOLLOW && openF) return 0;
#endif

    if (g.mode == MODE_WALLFOLLOW) {
        if (g.hand > 0) {                       /* left-hand rule */
            if (openL) return +1;
            if (openF) return  0;
            if (openR) return -1;
            return 2;
        } else {                                /* right-hand rule */
            if (openR) return -1;
            if (openF) return  0;
            if (openL) return +1;
            return 2;
        }
    }

    /* ---- Tremaux: prefer the passage we have used least ---- */
    uint8_t here = dir_of_heading(g.heading);
    Junction *j = junction_at(g.x_mm, g.y_mm, 1);
    if (!j) {                       /* memory full: fall back to the hand rule */
        if (g.hand > 0) { if (openL) return +1; if (openF) return 0; if (openR) return -1; }
        else            { if (openR) return -1; if (openF) return 0; if (openL) return +1; }
        return 2;
    }

    /* mark the passage we arrived through */
    mark_inc(j, (uint8_t)((here + 2) & 3));

    /* At the very first junction, the passage behind us is the start gate.
     * Burn it to "fully used" so the robot will only ever go back out of
     * its own start line if literally everything else has been tried. A
     * wall follower that laps the outer ring and calmly drives back out of
     * the front door is the single most common way to score nothing. */
    if (!g.first_decision_done) {
        g.first_decision_done = 1;
        mark_inc(j, (uint8_t)((here + 2) & 3));
        mark_inc(j, (uint8_t)((here + 2) & 3));
    }

    /* Candidates, in preference order. The marks decide; this list only
     * breaks ties - but on a maze the robot has not seen before, nearly
     * every decision IS a tie, so the order is what the route looks like.
     *
     * Straight goes first (STRAIGHT_FIRST), then the hand rule. That gives
     * the tidy path of a plain wall follower without the pivots in the
     * middle of open crossings, and the marks are still there underneath to
     * stop it walking away from road it has not driven yet. */
    int8_t  order[4];
    uint8_t opn[4];
    uint8_t k = 0;
#if STRAIGHT_FIRST
    order[k] =  0; opn[k] = openF; k++;
#endif
    if (g.hand > 0) {
        order[k] = +1; opn[k] = openL; k++;
#if !STRAIGHT_FIRST
        order[k] =  0; opn[k] = openF; k++;
#endif
        order[k] = -1; opn[k] = openR; k++;
    } else {
        order[k] = -1; opn[k] = openR; k++;
#if !STRAIGHT_FIRST
        order[k] =  0; opn[k] = openF; k++;
#endif
        order[k] = +1; opn[k] = openL; k++;
    }
    order[k] = 2; opn[k] = 1;       /* turning round is always possible */
    k++;

    int8_t  best = 2;
    uint8_t best_marks = 99;
    for (uint8_t i = 0; i < k; i++) {
        if (!opn[i]) continue;
        uint8_t d;
        if (order[i] == 2) d = (uint8_t)((here + 2) & 3);
        else               d = (uint8_t)((here + (int)order[i] + 4) & 3);
        uint8_t m = mark_get(j, d);
        if (m < best_marks) { best_marks = m; best = order[i]; }
    }

    uint8_t chosen = (best == 2) ? (uint8_t)((here + 2) & 3)
                                 : (uint8_t)((here + (int)best + 4) & 3);
    mark_inc(j, chosen);
    return best;
}

/* ------------------------------------------------------------------ */
/* Called at every decision point. Returns 1 if we are clearly livelocked. */
static uint8_t decision_burst(void)
{
    if ((g.dist_total_mm - g.last_decide_mm) < DECIDE_BURST_MM) {
        if (g.decide_burst < 255) g.decide_burst++;
    } else {
        g.decide_burst = 0;
    }
    g.last_decide_mm = g.dist_total_mm;
    if (g.decide_burst >= DECIDE_BURST_MAX) {
        g.decide_burst = 0;
        g.no_decide_until_mm = g.dist_total_mm + DECIDE_LOCKOUT_MM;
        return 1;
    }
    return 0;
}

static void enter_turn(int8_t quarters)
{
    float total = (quarters == 2) ? 180.0f : 90.0f * (float)quarters;
    g.turn_from_deg  = g.heading;
    g.turn_total_deg = total;
    g.turn_prof_deg  = 0.0f;
    g.turn_prof_dps  = 0.0f;
    g.target_deg = wrap180(g.target_deg + total);
    g.state = ST_TURN;
    g.state_t_ms = 0;
    g.turn_ok_ms = 0;
    g.prev_side_err = 0.0f;
}

static void snapshot(const NavIn *in)
{
    (void)in;
    g.snap_left  = g.open_l;
    g.snap_right = g.open_r;
    /* Debounced, NOT the raw reading. One dropped ping - and ultrasound
     * drops pings all the time - used to read as "the way ahead is clear",
     * which sent the robot straight into the wall it was standing in front
     * of, and from there into a U-turn and off the route entirely. */
    g.snap_front = g.open_f;
}

/* Debounce the side readings into steady "there is a gap here" flags, and
 * report the rising edge. Level-triggering would fire the instant the robot
 * rolls out of the start gate into open floor, before it has seen a single
 * wall - which is exactly the failure that eats a run in the first second. */
static void openings_update(const NavIn *in)
{
    uint8_t raw_l = (in->dist_left_mm  > OPEN_SIDE_MM);
    uint8_t raw_r = (in->dist_right_mm > OPEN_SIDE_MM);

    uint8_t raw_f = (in->dist_front_mm > FRONT_OPEN_MM);

    if (raw_l) { if (g.open_cnt_l < 12) g.open_cnt_l++; }
    else       { if (g.open_cnt_l > 0)  g.open_cnt_l--; }
    if (raw_r) { if (g.open_cnt_r < 12) g.open_cnt_r++; }
    else       { if (g.open_cnt_r > 0)  g.open_cnt_r--; }
    if (raw_f) { if (g.open_cnt_f < 12) g.open_cnt_f++; }
    else       { if (g.open_cnt_f > 0)  g.open_cnt_f--; }

    if (g.open_cnt_l >= OPEN_DEBOUNCE) g.open_l = 1;
    else if (g.open_cnt_l <= 3)        g.open_l = 0;
    if (g.open_cnt_r >= OPEN_DEBOUNCE) g.open_r = 1;
    else if (g.open_cnt_r <= 3)        g.open_r = 0;
    if (g.open_cnt_f >= OPEN_DEBOUNCE) g.open_f = 1;
    else if (g.open_cnt_f <= 3)        g.open_f = 0;
}

/* An opening seen on the way in stays remembered, because by the time the
 * axle reaches the junction the side sensor may already be past the gap. */
static void snapshot_merge(const NavIn *in)
{
    (void)in;
    if (g.open_l) g.snap_left  = 1;
    if (g.open_r) g.snap_right = 1;
    g.snap_front = g.open_f;
}

/* ------------------------------------------------------------------ */
NAV_API void nav_step(const NavIn *in, NavOut *out)
{
    float dt_s = (in->dt_ms > 0) ? (in->dt_ms / 1000.0f) : 0.02f;
    g.t_ms       += in->dt_ms;
    g.state_t_ms += in->dt_ms;

    odom_update(in);
    line_update(in);

    uint8_t was_open_l = g.open_l, was_open_r = g.open_r;
    openings_update(in);
    uint8_t edge_l = (g.open_l && !was_open_l);
    uint8_t edge_r = (g.open_r && !was_open_r);

    /* --- wedged? --- Motors commanded, wheels not turning: something is
     * jammed against a wall. This has to be watched in every moving state,
     * not just while driving straight - a robot that jams mid-pivot is the
     * classic way to lose a run. */
    uint8_t moving = (g.state == ST_DRIVE || g.state == ST_CREEP ||
                      g.state == ST_BACKUP || g.state == ST_TURN);
    if (moving && g.last_cmd_mag >= PWM_MIN) {
        if (in->ticks_left == g.stuck_tl && in->ticks_right == g.stuck_tr) {
            g.stuck_ms += in->dt_ms;
        } else {
            g.stuck_ms = 0;
            g.stuck_tl = in->ticks_left;
            g.stuck_tr = in->ticks_right;
        }
    } else {
        g.stuck_ms = 0;
        g.stuck_tl = in->ticks_left;
        g.stuck_tr = in->ticks_right;
    }
    if (g.stuck_ms > STUCK_WINDOW_MS) {
        g.stuck_ms = 0;
        g.stuck_escapes++;
        g.resume_turn = 0;
        g.backup_start_mm = g.dist_total_mm;
        g.state = ST_STUCK_RECOVER;
        g.state_t_ms = 0;
    }

    int16_t base = 0;
    float   steer = 0.0f;

    switch (g.state) {

    /* ---------------------------------------------------------- */
    case ST_BOOT:
        g.state = ST_WAIT_START;
        g.state_t_ms = 0;
        break;

    /* Autonomous start: hold a hand ~5 cm in front of the nose, then take
     * it away. No radio, no laptop, nothing to touch.
     *
     * The length of the hold also picks which wall we follow, so you can
     * change strategy at the start line after looking at the map without
     * opening a laptop:
     *      quick tap  (< 1.5 s)  -> LEFT-hand rule
     *      long hold  (> 1.5 s)  -> RIGHT-hand rule
     * The countdown then blinks slow for left, fast for right. */
    case ST_WAIT_START:
        /* A hand is between US_MIN_MM and 80 mm away, and has to STAY there
         * for START_ARM_MS before it counts.
         *
         * Both halves of that are guarding against a real failure. Anything
         * below US_MIN_MM is not a distance an HC-SR04 can produce, so it
         * means "no reading yet" - and treating it as a hand is what made
         * the robot start its own run seconds after power-on. Requiring the
         * hand to persist means no single glitched ping can ever start a
         * run, which is worth far more than starting a fraction of a second
         * sooner. */
        if (in->dist_front_mm >= US_MIN_MM && in->dist_front_mm < 80) {
            g.arm_ms += in->dt_ms;
            if (g.arm_ms >= START_ARM_MS) g.start_armed = 1;
        } else if (g.start_armed && in->dist_front_mm > 200) {
            g.hand = (g.arm_ms >= 1500) ? -1 : +1;
            g.state = ST_COUNTDOWN; g.state_t_ms = 0;
        } else if (!g.start_armed) {
            g.arm_ms = 0;          /* glitches must not accumulate into a start */
        }
        if (in->start_signal) { g.state = ST_COUNTDOWN; g.state_t_ms = 0; }
        break;

    case ST_COUNTDOWN:
        /* three seconds of blinking so the judges can see it is autonomous */
        if (g.state_t_ms >= 3000) {
            /* zero everything here: this pose is the origin of the run */
            g.heading = 0.0f;
            g.target_deg = 0.0f;
            g.x_mm = g.y_mm = 0.0f;
            g.dist_total_mm = 0.0f;
            enter_drive();
        }
        break;

    /* ---------------------------------------------------------- */
    case ST_DRIVE: {
        g.run_t_ms += in->dt_ms;

        /* --- are we out of the maze? ---
         * Open on every side AND well away from where we started, so
         * reversing back out of the start gate is never mistaken for a
         * finish. */
        float from_origin = sqrtf(g.x_mm * g.x_mm + g.y_mm * g.y_mm);
        uint8_t wide_open = (in->dist_front_mm > 700 &&
                             in->dist_left_mm  > 700 &&
                             in->dist_right_mm > 700 &&
                             from_origin > 800.0f);
        if (wide_open && g.dist_total_mm > 600.0f) {
            g.dist_open_mm += g.last_d_mm;
            if (g.dist_open_mm > 450.0f) { g.state = ST_FINISH; g.state_t_ms = 0; break; }
        } else {
            g.dist_open_mm = 0.0f;
        }
#if HAS_LINE_SENSOR
        /* A burst of stripes under the nose is the finish gate.
         * Compiled out by default - see HAS_LINE_SENSOR in config.h for why
         * this particular shortcut is a good way to lose a map. */
        if (g.edge_burst >= 4 && from_origin > 800.0f) {
            g.state = ST_FINISH; g.state_t_ms = 0; break;
        }
#endif
        if (g.run_t_ms > RUN_TIMEOUT_MS) { g.state = ST_FINISH; g.state_t_ms = 0; break; }

        /* --- livelock guard ---
         * Deciding three times inside 250 mm means the robot is turning on
         * the spot arguing with itself, which is how a run quietly burns
         * three minutes without moving. Back out and drive on regardless. */
        if (g.dist_total_mm < g.no_decide_until_mm) {
            base = PWM_SLOW;
            steer = steer_command(in, dt_s);
            break;
        }

        /* --- junction? ---
         * Two ways to notice one: a wall appears ahead, or a side wall
         * that was there a moment ago is suddenly not. Either way we do
         * NOT pivot here - we creep until the wheel axle is in the middle
         * of the junction square, and pivot from there. */
        if (in->dist_front_mm < FRONT_TOOCLOSE_MM) {
            snapshot(in);
            g.backup_start_mm = g.dist_total_mm;
            g.state = ST_BACKUP; g.state_t_ms = 0;
            break;
        }

        if (in->dist_front_mm < FRONT_BLOCKED_MM) {
            snapshot(in);
            g.creep_by_front = 1;
            g.creep_target_mm = g.dist_total_mm + 600.0f;   /* safety stop */
            g.state = ST_CREEP; g.state_t_ms = 0;
            break;
        }

        if ((edge_l || edge_r) && g.dist_since_decision_mm > (float)CELL_MM * 0.5f) {
            snapshot(in);
            if (edge_l) g.snap_left = 1;
            if (edge_r) g.snap_right = 1;
            g.creep_by_front = 0;
            g.creep_target_mm = g.dist_total_mm + (float)CREEP_AFTER_OPEN_MM;
            g.state = ST_CREEP; g.state_t_ms = 0;
            break;
        }

        /* --- normal driving --- */
        /* Ease off smoothly as a wall comes up rather than stepping the
         * throttle down, which shakes the chassis and upsets the gyro. */
        base = PWM_CRUISE;
        if (in->dist_front_mm < 400) {
            float f = ((float)in->dist_front_mm - (float)FRONT_BLOCKED_MM)
                    / (400.0f - (float)FRONT_BLOCKED_MM);
            if (f < 0.0f) f = 0.0f;
            if (f > 1.0f) f = 1.0f;
            base = (int16_t)(PWM_SLOW + f * (PWM_CRUISE - PWM_SLOW));
        }
        steer = steer_command(in, dt_s);
        break;
    }

    /* ---------------------------------------------------------- */
    /* Line the wheel axle up with the middle of the junction, then decide.
     * If a wall is ahead we range off it, which is far more accurate than
     * dead reckoning; otherwise we count millimetres off the encoders. */
    case ST_CREEP: {
        base  = PWM_SLOW;
        steer = steer_command(in, dt_s);

        if (in->dist_front_mm < FRONT_TOOCLOSE_MM) {
            g.backup_start_mm = g.dist_total_mm;
            g.state = ST_BACKUP; g.state_t_ms = 0;
            break;
        }
        /* keep watching the sides while we roll in - a gap can open up
         * during the creep itself */
        if (edge_l) g.snap_left = 1;
        if (edge_r) g.snap_right = 1;

        /* Sonar gets us close, encoders finish the job. Once the wall is
         * near enough to measure accurately, work out exactly how much
         * further the axle has to travel and count it off the wheels. */
        if (g.creep_by_front && in->dist_front_mm <= FRONT_HANDOVER_MM) {
            float remain = (float)in->dist_front_mm + US_F_X_MM
                         - ((float)CORRIDOR_MM * 0.5f + (float)PIVOT_BACKOFF_MM);
            if (remain < 0.0f) remain = 0.0f;
            g.creep_target_mm = g.dist_total_mm + remain;
            g.creep_by_front = 0;
        }

        if ((!g.creep_by_front && g.dist_total_mm >= g.creep_target_mm)
                || g.state_t_ms > 2500) {
            snapshot_merge(in);
            int8_t q = choose_turn();
            g.dist_since_decision_mm = 0.0f;
            if (q == 0) { enter_drive(); }
            else        { enter_turn(q); }
        }
        break;
    }

    /* ---------------------------------------------------------- */
    case ST_BACKUP:
        base = -PWM_BACK;
        steer = 0.0f;
        if ((g.dist_total_mm - g.backup_start_mm) > 90.0f || g.state_t_ms > BACKUP_MS) {
            if (g.resume_turn) {
                /* we were mid-pivot and ran out of room; try again with
                 * some space behind us */
                g.resume_turn = 0;
                g.state = ST_TURN; g.state_t_ms = 0; g.turn_ok_ms = 0;
                break;
            }
            snapshot_merge(in);
            if (decision_burst()) { enter_drive(); break; }
            int8_t q = choose_turn();
            if (q == 0) { enter_drive(); }
            else        { enter_turn(q); }
        }
        break;

    /* ---------------------------------------------------------- */
    case ST_TURN: {
        if (g.state_t_ms < TURN_SETTLE_IN_MS) {
            /* stand still for a moment: pivoting while still rolling
             * forward is what puts a corner of the chassis into a wall */
            out->pwm_left = slew(g.out_l, 0); out->pwm_right = slew(g.out_r, 0);
            g.out_l = out->pwm_left; g.out_r = out->pwm_right;
            g.last_cmd_mag = 0;
            out->state = g.state; out->done = 0; out->led = 1;
            out->sectors_seen = g.sectors;
            out->dbg_target_deg = g.target_deg; out->dbg_steer = 0.0f;
            return;
        }
        /* --- generate the profile one tick at a time ---------------
         * Ramp up at TURN_ALPHA, hold at TURN_OMEGA, and start braking at
         * exactly the point where TURN_ALPHA can still bring us to a stop on
         * the target. Commanding the angle directly and letting a P term
         * sort it out slams the motors to full and then hunts; a profile
         * arrives smoothly and stops. */
        float dt_s2 = in->dt_ms / 1000.0f;
        float sgn   = (g.turn_total_deg >= 0.0f) ? 1.0f : -1.0f;
        float swept = g.turn_prof_deg * sgn;
        float total = g.turn_total_deg * sgn;
        float remain = total - swept;
        if (remain < 0.0f) remain = 0.0f;

        float w_brake = sqrtf(2.0f * TURN_ALPHA_DPS2 * remain);
        float w_cmd   = (w_brake < TURN_OMEGA_DPS) ? w_brake : TURN_OMEGA_DPS;
        float w_accel = g.turn_prof_dps + TURN_ALPHA_DPS2 * dt_s2;
        if (w_cmd > w_accel) w_cmd = w_accel;
        if (w_cmd < 0.0f) w_cmd = 0.0f;
        g.turn_prof_dps  = w_cmd;
        g.turn_prof_deg += sgn * w_cmd * dt_s2;
        if ((g.turn_prof_deg * sgn) > total) g.turn_prof_deg = g.turn_total_deg;

        /* --- follow it: feed-forward plus a small PD correction ---- */
        float aim = wrap180(g.turn_from_deg + g.turn_prof_deg);
        float err = wrap180(aim - g.heading);
        float rate_err = (sgn * w_cmd) - in->gyro_rate_dps;

        /* Feed-forward: the PWM that already produces this rate, so the PD
         * terms only have to clean up the difference. PWM_MIN is the motor's
         * dead zone - below it nothing turns at all - so it is added as an
         * offset, not scaled. */
        float mag = TURN_FF * w_cmd;
        if (w_cmd > 1.0f) mag += (float)PWM_MIN;
        float cmd = sgn * mag + KP_TURN * err + KD_TURN * rate_err;

        int16_t t;
        if (w_cmd <= 0.0f) {
            float fe = wrap180(g.target_deg - g.heading);
            if (fe < 0) fe = -fe;
            /* Profile done. Inside tolerance command nothing at all - the
             * motor deadband would otherwise force 55 PWM and the robot
             * would hunt across the target until the turn timed out. */
            t = (fe < TURN_TOL_DEG) ? 0 : deadband(clamp16(
                    KP_TURN * wrap180(g.target_deg - g.heading), -PWM_TURN, PWM_TURN));
        } else {
            t = clamp16(cmd, -PWM_TURN, PWM_TURN);
            t = deadband(t);
        }
        int16_t tl = slew(g.out_l, (int16_t)(-t));
        int16_t tr = slew(g.out_r, (int16_t)(+t));
        g.out_l = tl; g.out_r = tr;
        g.last_cmd_mag = (t < 0) ? (int16_t)(-t) : t;
        out->pwm_left  = tl;
        out->pwm_right = tr;

        /* The pivot is finished when the PROFILE has run out and the real
         * heading has settled on the target - not merely when it passes
         * through it on the way past. */
        float fin = wrap180(g.target_deg - g.heading);
        if (fin < 0) fin = -fin;
        if (fin < TURN_TOL_DEG && remain <= 0.0f) {
            g.turn_ok_ms += in->dt_ms;
        } else {
            g.turn_ok_ms = 0;
        }
        if (g.state_t_ms > TURN_TIMEOUT_MS && g.turn_ok_ms < TURN_SETTLE_MS) {
            /* Out of time and still not pointing the right way: almost
             * always a corner of the body touching a wall. Reverse a little
             * and finish the same turn rather than setting off at an angle. */
            if (g.turn_retries < 2) {
                g.turn_retries++;
                g.resume_turn = 1;
                g.backup_start_mm = g.dist_total_mm;
                g.state = ST_BACKUP; g.state_t_ms = 0;
            } else {
                g.turn_retries = 0;
                g.target_deg = 90.0f * lroundf(g.heading / 90.0f);
                enter_drive_turned();
            }
        } else if (g.turn_ok_ms >= TURN_SETTLE_MS) {
            /* snap the target to the nearest quarter turn so gyro drift can
             * never accumulate from one corner to the next */
            g.turn_retries = 0;
            g.target_deg = 90.0f * lroundf(g.target_deg / 90.0f);
            /* We have just finished lining up with a corridor, so this is
             * the most trustworthy heading we will ever have. Call it exact
             * and the gyro's error stops accumulating from corner to
             * corner - it only ever has to survive one turn. */
            g.heading = g.target_deg;
            enter_drive_turned();
        }
        out->state = g.state;
        out->done  = 0;
        out->led   = 1;
        out->sectors_seen = g.sectors;
        out->dbg_target_deg = g.target_deg;
        out->dbg_steer = 0.0f;
        return;                     /* turn writes its own PWM, skip the mixer */
    }

    /* ---------------------------------------------------------- */
    case ST_STUCK_RECOVER:
        base = -PWM_BACK;
        steer = (g.stuck_escapes & 1) ? 45.0f : -45.0f;
        if (g.state_t_ms > 600) {
            g.stuck_tl = in->ticks_left;
            g.stuck_tr = in->ticks_right;
            enter_drive_turned();
        }
        break;

    /* ---------------------------------------------------------- */
    case ST_FINISH:
    default:
        base = 0; steer = 0.0f;
        g.done = 1;
        break;
    }

    /* ------------- mix and clamp ------------- */
    float l = (float)base - steer;
    float r = (float)base + steer;
    int16_t li = clamp16(l, -PWM_MAX, PWM_MAX);
    int16_t ri = clamp16(r, -PWM_MAX, PWM_MAX);
    if (base != 0) { li = deadband(li); ri = deadband(ri); }
    else           { li = 0; ri = 0; }

    li = slew(g.out_l, li);
    ri = slew(g.out_r, ri);
    g.out_l = li; g.out_r = ri;
    g.last_cmd_mag = (int16_t)((li < 0 ? -li : li) > (ri < 0 ? -ri : ri)
                               ? (li < 0 ? -li : li) : (ri < 0 ? -ri : ri));
    out->pwm_left  = li;
    out->pwm_right = ri;
    out->state     = g.state;
    out->done      = g.done;
    /* countdown blink: slow = left-hand rule, fast = right-hand rule */
    uint16_t blink = (g.hand > 0) ? 400 : 130;
    out->led       = (g.state == ST_COUNTDOWN) ? (uint8_t)((g.state_t_ms / blink) & 1)
                                               : (uint8_t)(g.state == ST_FINISH);
    out->sectors_seen   = g.sectors;
    out->dbg_target_deg = g.target_deg;
    out->dbg_steer      = steer;
}

/* ------------------------------------------------------------------ */
NAV_API const char *nav_state_name(uint8_t s)
{
    switch (s) {
    case ST_BOOT:          return "BOOT";
    case ST_WAIT_START:    return "WAIT_START";
    case ST_COUNTDOWN:     return "COUNTDOWN";
    case ST_DRIVE:         return "DRIVE";
    case ST_CREEP:         return "CREEP";
    case ST_BACKUP:        return "BACKUP";
    case ST_TURN:          return "TURN";
    case ST_STUCK_RECOVER: return "STUCK";
    case ST_FINISH:        return "FINISH";
    default:               return "?";
    }
}

NAV_API int32_t  nav_odom_x_mm(void)     { return (int32_t)g.x_mm; }
NAV_API int32_t  nav_odom_y_mm(void)     { return (int32_t)g.y_mm; }
NAV_API int32_t  nav_junction_count(void){ return (int32_t)g.njunc; }
NAV_API uint32_t nav_memory_bytes(void)  { return (uint32_t)(g.njunc * sizeof(Junction)); }

NAV_API uint32_t nav_export_memory(uint8_t *buf, uint32_t buf_len)
{
    uint32_t need = (uint32_t)(g.njunc * sizeof(Junction));
    if (buf_len < need) return 0;
    memcpy(buf, g.junc, need);
    return need;
}

NAV_API void nav_import_memory(const uint8_t *buf, uint32_t buf_len)
{
    uint32_t n = buf_len / sizeof(Junction);
    if (n > MAX_JUNCTIONS) n = MAX_JUNCTIONS;
    memcpy(g.junc, buf, n * sizeof(Junction));
    g.njunc = (uint8_t)n;
}

/* ================= MazeRunner.ino ================= */
/* =====================================================================
 * MazeRunner - Robotics Navigation Challenge
 * Arduino Uno R3 + L298N + 3x HC-SR04 + MPU-6050 + 2x slot encoders
 *
 * This file is ONLY hardware: pins, timers, I2C, PWM.
 * All the thinking happens in nav_core.cpp, which is also compiled into
 * the desktop simulator. Do not put navigation logic in here.
 *
 * Board:  Arduino Uno    Port: whatever the CH340 shows up as
 * Libraries needed: none (Wire and EEPROM ship with the IDE)
 * ===================================================================== */


/* ===================================================================== */
/* Ultrasonics - serviced one at a time, front twice as often as the sides */
/* ===================================================================== */
struct Sonar { uint8_t trig, echo; uint16_t mm; uint8_t fails; };
static Sonar sonarF = { PIN_TRIG_F, PIN_ECHO_F, US_MAX_MM, 0 };
static Sonar sonarL = { PIN_TRIG_L, PIN_ECHO_L, US_MAX_MM, 0 };
static Sonar sonarR = { PIN_TRIG_R, PIN_ECHO_R, US_MAX_MM, 0 };

/* 2 m of air, there and back, at 343 m/s = 11.7 ms. 13 ms is a safe cap. */
static const unsigned long ECHO_TIMEOUT_US = 13000UL;

static void sonarPing(Sonar &s)
{
  digitalWrite(s.trig, LOW);  delayMicroseconds(3);
  digitalWrite(s.trig, HIGH); delayMicroseconds(10);
  digitalWrite(s.trig, LOW);

  unsigned long us = pulseIn(s.echo, HIGH, ECHO_TIMEOUT_US);
  if (us == 0) {
    /* No echo. Either nothing is there, or the wall is at a bad angle and
     * the ping bounced away. Both mean "far" as far as we care. Two
     * misses in a row before we believe it, so one bad ping cannot make
     * the robot think a wall vanished. */
    if (s.fails < 3) s.fails++;
    if (s.fails >= 2) s.mm = US_MAX_MM;
    return;
  }
  s.fails = 0;

  uint16_t mm = (uint16_t)(us * 343UL / 2000UL);   /* us -> mm */
  if (mm < US_MIN_MM) mm = US_MIN_MM;
  if (mm > US_MAX_MM) mm = US_MAX_MM;

  /* median-of-3 on the fly: cheap, kills the classic single-sample spike */
  static uint16_t h[3][3]; static uint8_t hi[3]; static uint8_t primed[3];
  uint8_t k = (&s == &sonarF) ? 0 : (&s == &sonarL) ? 1 : 2;

  /* PRIME ALL THREE SLOTS with the first real reading, do not let them
   * start at zero.
   *
   * This mattered more than it looks. A zero-initialised history makes the
   * first ping report median(602, 0, 0) = 0 - a wall zero millimetres from
   * the nose. WAIT_START reads that as a hand held up to arm the start, and
   * two pings later, when the history has filled and the reading jumps to
   * its true value, it reads that as the hand being taken away. The robot
   * then started its own run about three seconds after power-on, with
   * nobody touching it. On the day that means it drives off the table while
   * you are still placing it.
   *
   * Found in Wokwi, not in the simulator: the simulator primes its own
   * history correctly, so the two disagreed. */
  if (!primed[k]) {
    h[k][0] = h[k][1] = h[k][2] = mm;
    primed[k] = 1;
  } else {
    h[k][hi[k]] = mm; hi[k] = (hi[k] + 1) % 3;
  }

  uint16_t a = h[k][0], b = h[k][1], c = h[k][2];
  uint16_t med = (a > b) ? ((b > c) ? b : ((a > c) ? c : a))
                         : ((a > c) ? a : ((b > c) ? c : b));
  s.mm = med;
}

/* ===================================================================== */
/* Wheel encoders - single channel, so direction comes from the command   */
/* ===================================================================== */
volatile int32_t encL = 0, encR = 0;
volatile int8_t  dirL = 1, dirR = 1;

static void isrL() { encL += dirL; }
static void isrR() { encR += dirR; }

/* ===================================================================== */
/* MPU-6050 - raw I2C, no library, so nothing can fail to install         */
/* ===================================================================== */
static const uint8_t MPU = 0x68;
static float gyroBiasZ = 0.0f;
static float headingDeg = 0.0f;
static float gyroRateDps = 0.0f;
static bool  gyroOK = false;

/* Set to -1 if you bolt the MPU on upside down. */
static const float GYRO_Z_SIGN = +1.0f;

static void mpuWrite(uint8_t reg, uint8_t val)
{
  Wire.beginTransmission(MPU); Wire.write(reg); Wire.write(val); Wire.endTransmission();
}

static int16_t mpuReadGyroZ()
{
  Wire.beginTransmission(MPU); Wire.write(0x47); Wire.endTransmission(false);
  Wire.requestFrom((int)MPU, 2);
  if (Wire.available() < 2) return 0;
  int16_t hi = Wire.read(), lo = Wire.read();
  return (int16_t)((hi << 8) | lo);
}

static bool mpuBegin()
{
  Wire.begin();
  Wire.setClock(400000);
  Wire.beginTransmission(MPU);
  if (Wire.endTransmission() != 0) return false;

  mpuWrite(0x6B, 0x01);   /* wake, clock from gyro X                       */
  delay(50);
  mpuWrite(0x1A, 0x03);   /* DLPF 44 Hz - kills motor vibration            */
  mpuWrite(0x1B, 0x08);   /* gyro full scale +/-500 dps -> 65.5 LSB/dps    */
  mpuWrite(0x19, 0x04);   /* sample rate 200 Hz                            */
  delay(50);

  /* Bias calibration. THE ROBOT MUST BE COMPLETELY STILL FOR THIS. */
  long sum = 0;
  const int N = 800;
  for (int i = 0; i < N; i++) { sum += mpuReadGyroZ(); delay(3); }
  gyroBiasZ = (float)sum / (float)N;
  return true;
}

/* Report the rate only. nav_core does the integrating, the deadband and
 * the re-biasing, because that is the part that has to be tested in the
 * simulator - and the simulator cannot run this file. headingDeg below is
 * for the serial log and for your eyes, nothing steers by it. */
static void gyroUpdate(float dt_s)
{
  if (!gyroOK) return;
  float raw = (float)mpuReadGyroZ() - gyroBiasZ;
  gyroRateDps = GYRO_Z_SIGN * raw / 65.5f;
  headingDeg += gyroRateDps * dt_s;
}

/* ===================================================================== */
/* L298N                                                                  */
/* ===================================================================== */
static void motorsBegin()
{
  pinMode(PIN_ENA, OUTPUT); pinMode(PIN_ENB, OUTPUT);
  pinMode(PIN_IN1, OUTPUT); pinMode(PIN_IN2, OUTPUT);
  pinMode(PIN_IN3, OUTPUT); pinMode(PIN_IN4, OUTPUT);
  analogWrite(PIN_ENA, 0);  analogWrite(PIN_ENB, 0);
}

static void motorsWrite(int16_t l, int16_t r)
{
  l *= MOTOR_L_SIGN;
  r *= MOTOR_R_SIGN;

  dirL = (l >= 0) ? 1 : -1;
  dirR = (r >= 0) ? 1 : -1;

  /* LEFT motor -> ENB / IN3,IN4 */
  digitalWrite(PIN_IN3, l >= 0 ? HIGH : LOW);
  digitalWrite(PIN_IN4, l >= 0 ? LOW  : HIGH);
  analogWrite(PIN_ENB, (uint8_t)constrain(abs(l), 0, 255));

  /* RIGHT motor -> ENA / IN1,IN2 */
  digitalWrite(PIN_IN1, r >= 0 ? HIGH : LOW);
  digitalWrite(PIN_IN2, r >= 0 ? LOW  : HIGH);
  analogWrite(PIN_ENA, (uint8_t)constrain(abs(r), 0, 255));
}

/* ===================================================================== */
/* EEPROM - the Uno already has 1024 bytes on board. No memory module,    */
/* no extra chip, nothing to buy. This is where the junction map lives    */
/* so a stopped-and-restarted run does not start from zero knowledge.     */
/* ===================================================================== */
static void memorySave()
{
  uint8_t buf[MAX_JUNCTIONS * 4];
  uint32_t n = nav_export_memory(buf, sizeof(buf));
  int a = EEPROM_BASE;
  EEPROM.update(a++, (uint8_t)(EEPROM_MAGIC >> 8));
  EEPROM.update(a++, (uint8_t)(EEPROM_MAGIC & 0xFF));
  EEPROM.update(a++, (uint8_t)(n >> 8));
  EEPROM.update(a++, (uint8_t)(n & 0xFF));
  for (uint32_t i = 0; i < n && a < 1000; i++) EEPROM.update(a++, buf[i]);
}

static void memoryLoad()
{
  int a = EEPROM_BASE;
  uint16_t magic = ((uint16_t)EEPROM.read(a) << 8) | EEPROM.read(a + 1);
  if (magic != EEPROM_MAGIC) return;
  uint16_t n = ((uint16_t)EEPROM.read(a + 2) << 8) | EEPROM.read(a + 3);
  if (n == 0 || n > MAX_JUNCTIONS * 4) return;
  static uint8_t buf[MAX_JUNCTIONS * 4];
  for (uint16_t i = 0; i < n; i++) buf[i] = EEPROM.read(a + 4 + i);
  nav_import_memory(buf, n);
}

static void memoryClear()
{
  EEPROM.update(EEPROM_BASE, 0); EEPROM.update(EEPROM_BASE + 1, 0);
}

/* ===================================================================== */
/* GO button - shares the LED pin, so it costs no extra pin                */
/*                                                                        */
/* Every pin on the Uno is already spoken for, so the button lives on D13
 * alongside the status LED. D13 is an OUTPUT driving the LED almost all of
 * the time; to read the button we flip it to INPUT_PULLUP for 200 us, take
 * a sample, and flip it straight back. The LED does not visibly flicker.
 *
 * WIRING:  button between D13 and GND, THROUGH A 330 ohm RESISTOR.
 * The resistor matters: without it, pressing the button while D13 is
 * driving the LED high is a dead short from the pin to ground.
 *
 * Only read while waiting to start - never while driving.
 * ===================================================================== */
/* The GO button has its own pin with the internal pull-up on, so a press is
 * simply a LOW. Nothing to share, nothing to fit, nothing to time. */
static bool goButtonPressed()
{
  return digitalRead(PIN_GO) == LOW;
}

/* ===================================================================== */
/* main                                                                   */
/* ===================================================================== */
static NavIn  nin;
static NavOut nout;
static unsigned long lastLoop = 0;
static uint8_t  sonarSlot = 0;
static bool     startPressed = false;
static bool     saved = false;

void setup()
{
  Serial.begin(115200);

  pinMode(sonarF.trig, OUTPUT); pinMode(sonarF.echo, INPUT);
  pinMode(sonarL.trig, OUTPUT); pinMode(sonarL.echo, INPUT);
  pinMode(sonarR.trig, OUTPUT); pinMode(sonarR.echo, INPUT);
#if HAS_LINE_SENSOR
  pinMode(PIN_LINE, INPUT);
#endif
  pinMode(PIN_GO, INPUT_PULLUP);   /* GO button to GND, no resistor needed */
  pinMode(PIN_LED, OUTPUT);

  motorsBegin();
  motorsWrite(0, 0);

#if HAS_ENCODERS
  pinMode(PIN_ENC_L, INPUT); pinMode(PIN_ENC_R, INPUT);
  attachInterrupt(digitalPinToInterrupt(PIN_ENC_L), isrL, RISING);
  attachInterrupt(digitalPinToInterrupt(PIN_ENC_R), isrR, RISING);
#endif

  Serial.println(F("# MazeRunner booting - hold still, calibrating gyro"));
#if HAS_GYRO
  gyroOK = mpuBegin();
  Serial.print(F("# gyro ")); Serial.println(gyroOK ? F("OK") : F("NOT FOUND"));
#endif

  nav_reset(DEFAULT_MODE, WALL_HAND);
  /* Uncomment the next line only if you want run 2 to remember run 1.
   * For a fresh map, leave it commented so the robot starts clean. */
  /* memoryLoad(); */

  Serial.println(F("# ready. Press GO, or wave a hand in front of the nose."));
  Serial.println(F("t_ms,state,dF,dL,dR,head,tgt,encL,encR,pwmL,pwmR,sect"));
  lastLoop = millis();
}

void loop()
{
  unsigned long now = millis();
  unsigned long dt = now - lastLoop;
  if (dt < LOOP_DT_MS) return;
  lastLoop = now;

  /* --- sensors --- front, left, front, right --- */
  switch (sonarSlot) {
    case 0: case 2: sonarPing(sonarF); break;
    case 1:         sonarPing(sonarL); break;
    case 3:         sonarPing(sonarR); break;
  }
  sonarSlot = (sonarSlot + 1) & 3;

  gyroUpdate(dt / 1000.0f);

  /* Three ways to say go, all of them hands-off once it moves:
   *   - the GO button on D13
   *   - a hand held in front of the nose and taken away (see nav_core)
   *   - 'g' over the serial port, handy on the bench
   * The button is only sampled before the run starts. */
  if (!startPressed && nout.state <= ST_WAIT_START) {
    static uint8_t btnCount = 0;
    if (goButtonPressed()) {
      /* Two consecutive reads, 40 ms apart. Longer than any switch bounce,
       * short enough that an ordinary click registers - 3 reads needed a
       * deliberate press-and-hold and felt broken. */
      if (++btnCount >= 2) {
        startPressed = true;
        Serial.println(F("# GO pressed"));
      }
    } else {
      btnCount = 0;
    }
  }
  if (Serial.available()) { if (Serial.read() == 'g') startPressed = true; }

  noInterrupts();
  int32_t tl = encL, tr = encR;
  interrupts();

  nin.dist_front_mm = sonarF.mm;
  nin.dist_left_mm  = sonarL.mm;
  nin.dist_right_mm = sonarR.mm;
  nin.heading_deg   = headingDeg;
  nin.gyro_rate_dps = gyroRateDps;
  nin.ticks_left    = tl;
  nin.ticks_right   = tr;
#if HAS_LINE_SENSOR
  nin.line_black    = (digitalRead(PIN_LINE) == LOW) ? 1 : 0;
#else
  nin.line_black    = 0;
#endif
  nin.start_signal  = startPressed ? 1 : 0;
  nin.dt_ms         = (uint16_t)dt;

  nav_step(&nin, &nout);

  motorsWrite(nout.pwm_left, nout.pwm_right);
  digitalWrite(PIN_LED, nout.led ? HIGH : LOW);

  if (nout.done && !saved) { memorySave(); saved = true; }

  /* telemetry, every 100 ms, CSV - tools/telemetry_plot.py eats this */
  static unsigned long lastLog = 0;
  if (now - lastLog >= 100) {
    lastLog = now;
    Serial.print(now);              Serial.print(',');
    Serial.print(nav_state_name(nout.state)); Serial.print(',');
    Serial.print(nin.dist_front_mm); Serial.print(',');
    Serial.print(nin.dist_left_mm);  Serial.print(',');
    Serial.print(nin.dist_right_mm); Serial.print(',');
    Serial.print(headingDeg, 1);     Serial.print(',');
    Serial.print(nout.dbg_target_deg, 1); Serial.print(',');
    Serial.print(tl);                Serial.print(',');
    Serial.print(tr);                Serial.print(',');
    Serial.print(nout.pwm_left);     Serial.print(',');
    Serial.print(nout.pwm_right);    Serial.print(',');
    Serial.println(nout.sectors_seen);
  }
}
