#!/usr/bin/env python3
"""
make_wokwi_sketch.py - squash the four firmware files into one .ino.

Wokwi (and the Arduino IDE) are happiest with a sketch folder containing
several files. Pasting four files into four correctly-named tabs is four
chances to get it wrong, and the failure mode is a build error that looks
like a code bug:

    sketch.ino:15:10: fatal error: config.h: No such file or directory

So this script GENERATES wokwi/sketch.ino: every line of the real firmware,
in one file, in dependency order. One paste, nothing to name.

It is generated, never hand-edited, so it cannot drift from the firmware.
Re-run it after any change:

    python3 tools/make_wokwi_sketch.py
"""
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
FW = os.path.join(ROOT, "firmware", "MazeRunner")
OUT = os.path.join(ROOT, "wokwi", "sketch.ino")

# Dependency order. config.h first because everything reads it; nav_core.h
# before nav_core.cpp; the .ino last because it calls into the brain.
PARTS = ["config.h", "nav_core.h", "nav_core.cpp", "MazeRunner.ino"]

# Local includes get satisfied by the concatenation itself, so they have to
# go. System includes are hoisted to the top instead.
LOCAL_INC = re.compile(r'^\s*#\s*include\s*"([^"]+)"\s*$')
SYS_INC = re.compile(r'^\s*#\s*include\s*<([^>]+)>\s*$')

HEADER = """\
/* =====================================================================
 * MazeRunner - SINGLE FILE BUILD
 *
 * GENERATED by tools/make_wokwi_sketch.py - do not edit this file.
 * Edit the real sources in firmware/MazeRunner/ and re-run the script.
 *
 * This is every line of the four firmware files squashed into one, so it
 * can be pasted into a single Wokwi tab (or a single Arduino sketch) with
 * nothing else to set up. It is byte-for-byte the same code as
 *
 *      firmware/MazeRunner/config.h
 *      firmware/MazeRunner/nav_core.h
 *      firmware/MazeRunner/nav_core.cpp
 *      firmware/MazeRunner/MazeRunner.ino
 *
 * Board: Arduino Uno.  Libraries needed: none.
 * ===================================================================== */

"""


def main():
    sys_includes = []
    chunks = []

    for name in PARTS:
        path = os.path.join(FW, name)
        if not os.path.exists(path):
            sys.exit("missing source file: %s" % path)
        kept = []
        for line in open(path, encoding="utf-8").read().splitlines():
            if LOCAL_INC.match(line):
                continue                      # satisfied by concatenation
            m = SYS_INC.match(line)
            if m:
                if m.group(1) not in sys_includes:
                    sys_includes.append(m.group(1))
                continue                      # hoisted to the top
            kept.append(line)
        body = "\n".join(kept).strip("\n")
        chunks.append("/* ================= %s ================= */\n%s"
                      % (name, body))

    text = HEADER
    text += "\n".join("#include <%s>" % h for h in sys_includes) + "\n\n"
    text += "\n\n".join(chunks) + "\n"

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write(text)

    # Sanity: nothing may still be trying to #include a local file, and the
    # preprocessor has to balance or the paste will fail in a confusing way.
    depth = 0
    for n, line in enumerate(text.splitlines(), 1):
        if LOCAL_INC.match(line):
            sys.exit("line %d still has a local include: %s" % (n, line))
        s = line.strip()
        if re.match(r'#\s*(if|ifdef|ifndef)\b', s):
            depth += 1
        elif re.match(r'#\s*endif\b', s):
            depth -= 1
            if depth < 0:
                sys.exit("unbalanced #endif at line %d" % n)
    if depth != 0:
        sys.exit("unbalanced preprocessor: %d block(s) left open" % depth)

    print("wrote %s" % os.path.relpath(OUT, ROOT))
    print("  %d lines, %d KB, includes: %s"
          % (len(text.splitlines()), len(text) // 1024,
             ", ".join(sys_includes)))


if __name__ == "__main__":
    main()
